name: CWV Daily Report

permissions:
  contents: write

on:
  schedule:
    # 毎日 0:00 UTC = 日本標準時 09:00
    - cron: "0 0 * * *"
  workflow_dispatch:   # 手動実行も許可

concurrency:
  group: cwv_daily
  cancel-in-progress: false

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install system fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y fonts-noto-cjk

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "requirements.txt"

      - name: Install dependencies
        run: |
          pip install --quiet requests pandas matplotlib slack_sdk python-dotenv

      - name: Run CWV report script
        env:
          CRUX_API_KEY:      ${{ secrets.CRUX_API_KEY }}
          PSI_API_KEY:       ${{ secrets.PSI_API_KEY }}
          SLACK_BOT_TOKEN:   ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID:  ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          ORIGIN_URL:        "https://good-apps.jp"
          URL_TOTAL_COUNT:   "0"
        run: python scripts/cwv_report.py

      - name: Commit updated history (if changed)
        run: |
          if ! git diff --quiet --exit-code data/cwv_history.csv; then
            git config --global user.email "actions@github.com"
            git config --global user.name  "github-actions"
            git add data/cwv_history.csv
            git commit -m "Update CWV history ($(date '+%Y-%m-%d'))"
            git push
          fi
