name: CWV Daily Report

on:
  schedule:
    - cron: '0 23 * * *' # JST 8:00 = UTC 23:00 (前日)
  workflow_dispatch:

jobs:
  cwv-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install matplotlib requests

      - name: Run CWV Report
        env:
          CRUX_API_KEY: ${{ secrets.CRUX_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          ORIGIN: ${{ secrets.ORIGIN }}
          SITEMAP_URL: ${{ secrets.SITEMAP_URL }}
        run: python scripts/cwv_report.py
