name: CWV Daily Report

on:
  schedule:
    # 毎日 0:00 UTC = 日本標準時 09:00
    - cron: "0 0 * * *"
  workflow_dispatch:   # 手動実行も許可

concurrency:
  group: cwv_daily
  cancel-in-progress: false

jobs:
  report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install --quiet requests pandas matplotlib slack_sdk python-dotenv

      - name: Run CWV report script
        env:
          CRUX_API_KEY:      ${{ secrets.CRUX_API_KEY }}
          PSI_API_KEY:       ${{ secrets.PSI_API_KEY }}
          SLACK_BOT_TOKEN:   ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID:  ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # 未設定なら空
          ORIGIN_URL:        "https://good-apps.jp"
          URL_TOTAL_COUNT:   "1200"          # 観測できるURL総数 (目安)。必要に応じて調整
        run: python scripts/cwv_report.py

      - name: Commit updated history (if changed)
        run: |
          if [[ `git status --porcelain data/cwv_history.csv | wc -l` -gt 0 ]]; then
            git config --global user.email "actions@github.com"
            git config --global user.name  "github-actions"
            git add data/cwv_history.csv
            git commit -m "Update CWV history ($(date '+%Y-%m-%d'))"
            git push
          fi
