name: CrUX Web Vitals Report

on:
  # JST 08:00 (= UTC 前日 23:00)
  schedule:
    - cron:  '0 23 * * *'
  workflow_dispatch: {}

jobs:
  report:
    runs-on: ubuntu-latest

    # ジョブレベル env ― ここに **すべて** 集約
    env:
      CRUX_API_KEY:      ${{ secrets.CRUX_API_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      SLACK_BOT_TOKEN:   ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID:  ${{ secrets.SLACK_CHANNEL_ID }}
      ORIGIN:            "https://good-apps.jp"
      SITEMAP_URL:       "https://good-apps.jp/sitemap.xml"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: python -m pip install --no-cache-dir requests matplotlib pillow

      - name: Run CWV daily reporter
        run: python scripts/cwv_report.py
